### PR TITLE
Improve Anki support

### PR DESCRIPTION
**Pull request by tatsumoto-ren**
This PR adds an ability to configure the "Word" and "Definition" fields. It is also possible to include the entire search string on a card as a "Sentence" field.

https://user-images.githubusercontent.com/69171671/224502179-27b89609-6bf4-488a-87bc-2fa918bad3f2.mp4

### CODE REVIEW

**Comment by xiaoyifang** [comment]
Thanks for you contribution and welcome.
This is my understanding of this PR(correct me if I'm wrong):
this PR has offered the ability to configure the variables used in Anki.    which mean in orginal gd, anki can only use two variables called `Front` and `Back` which denotes the `word` and `selected text`
this PR has changed the variable names used in anki.
rename `Front` to `VocabKanji`,`Back` to `VocabDef`. and add a new variable called `Sentikanji`

In my viewpoint ,the configured word variables(word,text,sentence) can be fixed value,there is no need to configure them in different languages.
which means in Japanese , configured the variables as these(VocabKanji,VocabDef ,Sentikanji) is no neccessary.  the variables names can be fixed to avoid confusion.
the recommend fixed variable names can be `word`,`selected_text`,`marked_sentence` etc.  this will make the anki template unified and can be shared through different language.

I think the most importance improvement of this PR is that  a new variable called sentence_changed(`SentiKanji`) is added.

image

**Comment by tatsumoto-ren** [comment]
> this PR has offered the ability to configure the variables used in Anki. which mean in orginal gd, anki can only use two variables called Front and Back which denotes the word and selected text

Yes. Currently it's not possible to change them, which forces the user to create a Note Type with the fields named exactly "Front" and "Back". But since many users have their own custom Note Types, one set of fields can't be enough for everybody. 

> the configured word variables(word,text,sentence) can be fixed value

They are fixed now. The most important part of this PR is to let the user set their own fields. I think by default they can be called "Word", "Sentence", "Definition", but it is absolutely essential that they are configurable since everybody has their own Note Types in Anki.

> he recommend fixed variable names can be word,selected_text,marked_sentence etc. this will make the anki template unified and can be shared through different language.

I don't mind any names being used by default. But I think it's important to be able to change them to adjust to the used Model (note type). Since the model name is already configurable, it makes sense to add options to configure the fields as well.

**Comment by xiaoyifang** [comment]
> I think by default they can be called "Word", "Sentence", "Definition",

this should also be ok.


I think other fields also can be provided ,such as  
`current dictionary name`
`the whole article text`
`pronounce audio `(can anki support audio stream etc.)
`dictionary icon `(if exists,  can pictures be send to anki?)



> but it is absolutely essential that they are configurable since everybody has their own Note Types in Anki.

the reasons I  want the names to be fixed value is that the more fields we provide ,the more complex the code（the configuration ,etc).

**Comment by tatsumoto-ren** [comment]
> I think other fields also can be provided ,such as
> current dictionary name
> the whole article text
> proniciation audio (can anki support audio stream etc.)
> dictionary icon (if exists, can pictures be send to anki?)

Those are great additions too. Yes, you can send audio and pictures to Anki through AnkiConnect. 

> the reasons I want the names to be fixed value is that the more fields we provide ,the more complex the code（the configuration ,etc).

I think we can deal with having a more complex configuration since the alternative is too limiting. It essentially forces everybody to use the same field names.

Here's how Yomichan handles Anki settings. You select your Model, then it lets you map its fields to whatever data Yomichan can generate.

screenshot-2023-03-15-14-45-51

**Pull request merged**
