### PR TITLE
remove qt-style.css content totally 

### PR DESCRIPTION
**Pull request by xiaoyifang**
related with #395

qss cause more trouble than achieved.

### CODE REVIEW

**Comment by shenlebantongying** [comment]
It looks like the thing beside it is still "damned".
Screenshot 2023-03-20 at 9 09 12 PM

Screenshot 2023-03-20 at 9 09 48 PM

**Comment by xiaoyifang** [comment]
remove `GroupComboBox` qss too?

**Comment by shenlebantongying** [comment]
The icon also have to be removed,
Screenshot 2023-03-20 at 9 37 23 PM

**Comment by xiaoyifang** [comment]
> 

done

**Comment by shenlebantongying** [comment]
It perfectly switch now, and it looks this, native macOS style:

The text is gone, (likely the same reason the tabbar's text also gone -> image + text causes wrong size calculation on macOS https://github.com/xiaoyifang/goldendict/issues/278)

Screenshot 2023-03-20 at 9 46 53 PM
Screenshot 2023-03-20 at 9 47 15 PM

**Comment by xiaoyifang** [comment]
https://github.com/xiaoyifang/goldendict/pull/403#issuecomment-1477170931

**Comment by xiaoyifang** [comment]
> The text is gone

does this caused by this PR.

**Comment by shenlebantongying** [comment]
Somehow yes, the qss added some extra padding.

**Comment by xiaoyifang** [comment]
set a minimum width to the comboxgroup?

**Comment by shenlebantongying** [comment]
No, the group text is not gone, but their color is not changed and looks like gone when theme switched.

**Comment by shenlebantongying** [comment]
If the icon is not added, then it will switch normally. https://github.com/xiaoyifang/goldendict/blob/7ac1877544aa5019a4329557c4941ee035e58f3b/groupcombobox.cc#L48
Screenshot 2023-03-20 at 10 05 22 PM

**Comment by shenlebantongying** [comment]
The problem looks like this:

https://user-images.githubusercontent.com/20123683/226503022-555ccc57-b0b4-4974-9e55-d07099fa826e.mov

**Comment by xiaoyifang** [comment]
image

**Comment by xiaoyifang** [comment]
> The problem looks like this:

qt bug?

**Comment by shenlebantongying** [comment]
Yes :)

QGroupCombox's text doesn't react to macOS's theme switching. (I tried to set the SizeAdjustPolicy and remove the icon but they are not related)

**Comment by shenlebantongying** [comment]
No, it is not. I tried on qbittorrent, but their ComboBox works.

**Comment by shenlebantongying** [comment]
Why don't we completely eliminate the qss?

The background color in side panels can be easily changed to yellow via setPalette.

https://github.com/xiaoyifang/goldendict/blob/7ac1877544aa5019a4329557c4941ee035e58f3b/mainwindow.cc#L1203-L1213

**Comment by xiaoyifang** [comment]
> Why don't we completely eliminate the qss?
> 
> The background color in side panels can be easily changed to yellow via setPalette.
> 
> https://github.com/xiaoyifang/goldendict/blob/7ac1877544aa5019a4329557c4941ee035e58f3b/mainwindow.cc#L1203-L1213

two different ways. I think no need to change unless it cause issues and can not achieve its goal

**Comment by shenlebantongying** [comment]
If all qt-style.css removed:

https://user-images.githubusercontent.com/20123683/226505307-3b990e62-de09-4ea7-8e35-5547346dd2a9.mov

**Comment by xiaoyifang** [comment]
well done
image
 seems larger than before

**Comment by xiaoyifang** [comment]
image

these two parts will affect function .   the other parts are only UI interfaces I think can be removed.

**Comment by shenlebantongying** [comment]
Removing all qss will also make Linux's theme switching perfect.

If we reimplement the yellow background on Windows with QPalette like the dark mode on Windows, then we will have perfect theme switching everywhere.

Not sure what desktop environment you have on linux, if the DE don't have qt theme switching, you can try qt5ct.

Before (menu bar and translate box doesn't follow color change):
Peek 2023-03-20 22-49

After:
Peek 2023-03-20 22-50

**Comment by xiaoyifang** [comment]
> If we reimplement the yellow background on Windows with QPalette like the dark mode on Windows,

we can limited the darkmode only on default display style

**Comment by shenlebantongying** [comment]
> these two parts will affect function . the other parts are only UI interfaces I think can be removed.
I think we can maybe replace it in LineEdit' painevent, just draw a half transparent rectangle on top of the entire LineEdit if the property noResult is true.

**Comment by shenlebantongying** [comment]
LGTM, but I am not sure about the impact to MainStatusBar.

**Comment by shenlebantongying** [comment]
Maybe we should add an option to switch display style on macOS.

The `fusion` style on macOS looks better than the default.

Screenshot 2023-03-21 at 9 42 26 AM
Screenshot 2023-03-21 at 9 43 42 AM

**Comment by xiaoyifang** [comment]
`goldendict -style fusion`

**Pull request merged**
