### PR TITLE
Add two basic "copy info" buttons to about dialog for easier bug reporting

### PR DESCRIPTION
**Pull request by shenlebantongying**
This will probably reduce the useless conversation of asking bug reporter's basic system info. They can just click that button rather than screenshot.

It will include flags only for linux users since they often build things themselves.

Sample output:
```
Goldendict 22.9.24-alpha.67485fd8 on Thu Nov 17 02:59:57 2022
arch linux 6.0.8-arch1-1 Qt 5.15.7 x86_64-little_endian-lp64
GCC 12.2.0
Flags: MAKE_EXTRA_TIFF_HANDLER
```

The "copy dictionaries list" does feel useless and i didn't figure out how to get what type of dict that a user are using. It is just a list of names.

Since qt6 requires c++17, i think the lambda usage is ok.

### CODE REVIEW

**Comment by xiaoyifang** [comment]
@shenlebantongying  some minor changes need to be fixed

**Comment by shenlebantongying** [comment]
What changes are needed in your mind? I think you can use the github's code review tool to add some comments between lines.

**Comment by xiaoyifang** [comment]
image

**Comment by shenlebantongying** [comment]
fixed @xiaoyifang

**Pull request merged**
