### PR TITLE
lingua: add safeguards to errors

### PR DESCRIPTION
**Pull request by shenlebantongying**
* set timeout to 6s
* get rid of reply with errors

related https://github.com/xiaoyifang/goldendict/issues/282#issuecomment-1366154091

### CODE REVIEW

**Comment by shenlebantongying** [comment]
Is 3s too low?

**Comment by xiaoyifang** [comment]
6s is a little longer than expected .
2s or 3s should be ok.

**Comment by shenlebantongying** [comment]
ok, changed to 3s

**Comment by xiaoyifang** [comment]
should `netReplies` pop the reply?

**Comment by shenlebantongying** [comment]
There is only one reply which contains the links, so no?

**Comment by shenlebantongying** [comment]
The boilerplate code are mostly copied from forvo.cc 

The 'netReplies' is probably not needed. Just one reply.

I am checking how dictionary.cc works in detail.

**Pull request merged**
