### PR TITLE
Marketing Overhaul README.md

### PR DESCRIPTION
**Pull request by shenlebantongying**
The structure is much cleaner now. No technical info was removed.

image

### CODE REVIEW

**Comment by shenlebantongying** [comment]
According to https://github.com/chetabahana/symlink symlink works for github pages.

We can make a symbolic link `/docs/index.md -> README.md` so that we can have a rendered page on https://xiaoyifang.github.io/goldendict/ then put the link on the right panel. The source tree lives in top level, and need too much scrolling to reach the README.

The Howtos can also be put on the the webpage

**Comment by shenlebantongying** [comment]
nvm, jekyll doesn't support symlink

**Comment by xiaoyifang** [comment]
does it conflict with https://github.com/xiaoyifang/goldendict/wiki

**Comment by shenlebantongying** [comment]
Conflict in what? wiki can be used for docs about all kinds of things. README and website are for essential info and marketing.

**Comment by shenlebantongying** [comment]
@xiaoyifang I think this is ready, you can view the page at:
https://shenlebantongying.github.io/goldendict/

And it will become
https://xiaoyifang.github.io/goldendict/

**Comment by xiaoyifang** [comment]
Can we  reference readme.md from doc.md but not the vice versa?

**Comment by shenlebantongying** [comment]
To have a proper website, we maybe need a separate repo. Problem is that Simple `.md` GitHub pages aren't customizable.

if `docs/index.md` is the real file, and README.md is just a link when the user clicks the README.md, GitHub will render its path as content. If a user shares "goldendict.git/README.md` to others, it becomes werid.

Also if we reference put a file on docs/index.md and make a . If

**Pull request merged**
