### PR TITLE
Truly Good Website

### PR DESCRIPTION
**Pull request by shenlebantongying**
See the result: https://shenlebantongying.github.io/goldendict/

This is what in my mind at https://github.com/xiaoyifang/goldendict/issues/353 but I have been too lazy to do it, but here it is :sweat_smile: 

We cannot develop new features without document them.

Not finished yet.

This should obsolete `/help/` `/docs/` `/howto/` :sweat_smile: 

---

The website is deployed to a separated branch `gh-pages`.

This is a well known git trick, by storing data in a branch that is not related to the main one. Run git collect garbage, the branch data will be removed.

In every deployment, that branch will be hard-reset, so there will be no insane repo size growing.

image

### CODE REVIEW

**Comment by xiaoyifang** [comment]
> The website is deployed to a separated branch `gh-pages`.

Currently I configured like below.
image

**Comment by xiaoyifang** [comment]
But I have to see the result is great

**Comment by shenlebantongying** [comment]
I think this is ready to be merged @xiaoyifang 

The contents include everything from the help file with some corrections, plus some extras. This is an upgrade in every way.

Just change the GitHub pages deployment branch to `gh-pages` after merge, and it will be online.

The mkdocs-material do have support for an [astonishing front page](https://squidfunk.github.io/mkdocs-material/), but I don't do web development, so no.

I think the basic features are good enough, so I don't pin a version. We just accept whatever improvements made by `mkdocs-material`'s developers :sweat_smile:

**Comment by xiaoyifang** [comment]
> Just change the GitHub pages deployment branch to `gh-pages` after merge

you mean the `gh-pages` workflow action

**Comment by shenlebantongying** [comment]
No, I mean the `gh-pages` branch.

The `mkdocs ghdeploy --force` in the workflow will hard reset `gh-pages` branch and put generated files to there. So on GitHub's side, it only needs to deploy a static website.

https://www.mkdocs.org/user-guide/deploying-your-docs/#project-pages
image

**Pull request merged**
